=== mellonis-edu/class-02-xml-xsd-xsl-json/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="class">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="student" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="firstName">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="1"/>
                                        <xs:maxLength value="15"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="lastName">
                                    <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:minLength value="1"/>
                                                <xs:maxLength value="15"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="teacher" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== mellonis-edu/class-02-xml-xsd-xsl-json/data.xml
<?xml version="1.0" encoding="UTF-8"?>
<class xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./schema.xsd">
    <student id="1">
        <firstName>Руслан</firstName>
        <lastName>Иванов</lastName>
    </student>
    <student id="2">
        <firstName>Людмила</firstName>
        <lastName>Петрова</lastName>
    </student>
    <teacher>Ruslan</teacher>
</class>
